<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviortree"
    nsURI="http://bt/1.0" nsPrefix="bt">
  <eClassifiers xsi:type="ecore:EClass" name="BEModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dbt" lowerBound="1" eType="#//BehaviorTree"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentList" lowerBound="1"
        eType="#//ComponentList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementList" lowerBound="1"
        eType="#//RequirementList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialE" eType="#//SpecialEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Composition">
    <eLiterals name="Sequential"/>
    <eLiterals name="Atomic" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Branch">
    <eLiterals name="Parallel"/>
    <eLiterals name="Alternative" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="Reference" literal="=>"/>
    <eLiterals name="Reversion" value="1" literal="^"/>
    <eLiterals name="BranchKill" value="2" literal="--"/>
    <eLiterals name="Synchronize" value="3" literal="@"/>
    <eLiterals name="Conjunction" value="4" literal="&amp;&amp;"/>
    <eLiterals name="Disjunction" value="5" literal="||"/>
    <eLiterals name="ExclusiveOR" value="6" literal="^^"/>
    <eLiterals name="NoOperator" value="7" literal=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BehaviorType">
    <eLiterals name="StateRealization" literal="StateRealization"/>
    <eLiterals name="Selection" value="1"/>
    <eLiterals name="Guard" value="2"/>
    <eLiterals name="InternalInput" value="3"/>
    <eLiterals name="InternaOutput" value="4"/>
    <eLiterals name="ExternalOutput" value="5"/>
    <eLiterals name="ExternalInput" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="InternalInput"/>
    <eLiterals name="InternalOutput" value="1"/>
    <eLiterals name="ExternalInput" value="2"/>
    <eLiterals name="ExternalOutput" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNode" lowerBound="1"
        upperBound="-1" eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" eType="#//Branch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" eType="#//Composition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SpecialEdgeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SpecialEdgeEnum">
    <eLiterals name="Reference" literal="=>"/>
    <eLiterals name="Reversion" value="1" literal="^"/>
    <eLiterals name="BranchKill" value="2" literal="--"/>
    <eLiterals name="Synchronize" value="4" literal="@"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceabilityStatus" eType="#//TraceabilityStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityLink" eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TraceabilityStatus">
    <eLiterals name="Original" literal=""/>
    <eLiterals name="Implied" value="1" literal="+"/>
    <eLiterals name="Missing" value="2" literal="-"/>
    <eLiterals name="Updated" value="3" literal="++"/>
    <eLiterals name="Deleted" value="4" literal="--"/>
    <eLiterals name="DesignRefinement" value="5" literal="+-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTo" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" upperBound="-1"
        eType="#//StandardNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Requirement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityLink" upperBound="-1"
        eType="#//StandardNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorType" eType="#//BehaviorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviorRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
  </eClassifiers>
  <eSubpackages name="behaviortree" nsURI="defaultname" nsPrefix="be.behaviortree.model"/>
</ecore:EPackage>
